### ISSUE TITLE
"modify" mode only lets the last vertex to be dragged with @deck.gl/layers >= 7.2 and @deck.gl/core >= 7.2 

### ISSUE THREAD

**Issue by lxe** [uber/nebula.gl#275]
#### Describe the bug

Only the final vertex is modifiable/draggable in `modify` mode.

#### Actual Result

![lastpoint mov](https://user-images.githubusercontent.com/1486609/64302943-88b31000-cf3a-11e9-9764-0d5f31cc5d65.gif)

#### Expected Result

All vertices should be modifiable and we should be able to add vertices on polygon edges.

#### Reproduce Steps

```
    "@deck.gl/core": "7.2.3",
    "@deck.gl/layers": "7.2.3",
    "@deck.gl/react": "7.2.3",
    "@nebula.gl/layers": "0.15.0-alpha.7",
```

https://codesandbox.io/s/gallant-hamilton-98v94

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by lxe** [comment]
Looks like downgrading @decl.gl/core and @deck.gl/layers to 7.1.11 fixes this!

**Comment by jonathanlarkin** [comment]
I experienced this issue as well. Downgrading to 7.1.11 resolved for me as well.

**Comment by jcready** [comment]
This is also blocking us from updating to the latest deck.gl.

**Comment by Pessimistress** [comment]
This should be fixed with `deck.gl@7.2.5`.

**Comment by jcready** [comment]
`deck.gl@7.2.5` fixes the ability to select and move all vertices, but we are still unable to click the edges between vertices to create a new one.

**Comment by Pessimistress** [comment]
Really fixed in `deck.gl@7.2.6`... /o\

**Comment by supersonicclay** [comment]
Verified it is working with 7.2.6. Thanks @Pessimistress!
